---
title: "manuscript 1"
author: "程诚柏然"
date: "`r Sys.Date()`"
output: 
 html_document:
   toc: true
   toc_float: true
---

# 课程导言

## 机器学习

两个部分：特征提取&模型建立（建模比较程序化）

什么是特征提取（两种方式：原始信号特征提取（eg. 功能连接矩阵）&对特征进行二次加工

什么是模型建立（线性模型、逻辑回归、甚至更为复杂的随机森林、梯度曲线树），不同的模型有不同的适用范围与数据格式

进一步细分：特征提取 =\> 特征编码 =\> 特征筛选 =\> 模型建立 =\> 模型解释

特征编码：意义。

特征筛选：全部特征分析不现实

模型建立：对选择后的特征建模

模型解释：解释模型的结果，有点像论文中的讨论部分？可与统计结果相互印证

## fmri和机器学习

主要应用于功能性图像（fmri）。也能够会涉及结构像。

1.  疾病诊断、状态识别（第一个是主要内容）
2.  探究神经机制、脑机制（计算神经科学内容。通过研究神经网络反过来研究实际神经机制）
3.  大脑神经模式分析（本课会有涉及）

## 理工科内部的不同

理学在于可解释性，能够理解，完整故事

工科在于用就完了，管它为什么

## 课程范围和术语

-   特征（任何数据都是特征，只要我们输入进模型）、被试、样本（这里的样本概念和普通心理学中有差异，是一个人为切割的概念）
-   静息态、任务态
-   TR、MNI
-   事件相关设计、组块设计

---

# python基础

## Spyder介绍

与pycharm不同，这个主要用于数据科学、pycharm视频里说在工程项目中用的多。

## python层次控制

```
%在MATLAB中使用end控制层次

if <condition>
   <statement>
   if <condition>
   <statement>
   end
end
```

```
#在python中使用TAB进行层次控制（也能用空格实现）

if <conditon>:
   <statement>
  if<condition>:
    <statement>
    
```

## python运算符

### 普通运算符

这里只记一下当初没第一眼搞懂的。

| 符号 | 意义     | 备注     |
|------|----------|----------|
| \%   | 取余数   | 5%2=1    |
| \*\* | n次方    | 2\*\*3=8 |
| //   | 向下整除 | 5//2=2   |
| ==   | 等于     |          |
| !=   | 不等于   |          |

还有一个运算缩写:`c + = a`为`c = c + a`，剩余的四则运算以此类推。

### 逻辑运算符

| 符号 | 意义     | 备注                                         |
|------|----------|----------------------------------------------|
| and  | 布尔“与” | x and y，如果x为F，就返回F，否则就返回y的值  |
| or   | 布尔“或” | x or y，如果x不等于0，则返回x值，否则返回y值 |
| not  | 布尔“非” | 违抗症状                                     |

## for循环语句

``` 
%matlab中的循环
for j in 1:10
    j
end
```

```
#python中的循环，注意第一行加**冒号冒号冒号**
for i in range(0, 10):
    print(i)
```

```
#python中的循环
for i in range(1, 10, 2):    #左闭右开区间，[begin, end, step]
    print(i)
```

```
#python中的循环
for i in range(10, -3, -4):
    print(i)
```

## while循环语句

这里主要还是得说一下for和while的区别

>想象一下你在一个水果店里。for 循环就像是你有一个水果篮子，里面有苹果、香蕉、橘子等等。你从第一个水果开始，一个接一个地拿出来看，直到篮子里没有水果了。在 Python 中，for 循环就是这样，它会遍历一个列表或者集合中的每一个元素。
>
>而 while 循环则像是你在等待一个特定的事件发生。比如，你在等待店里的打折活动开始。你会一直等，直到店员告诉你打折开始了。在 Python 中，while 循环会一直执行，直到某个条件不再满足为止。
>
>所以，如果你想要重复做某件事，直到达到某个特定的条件，就应该使用 while 循环。如果你有一组确定的元素需要逐一处理，就使用 for 循环。

## 判断语句

有一点我老是会忘记就是，python的条件判断if、elseif行还有else行的末尾，都要**加冒号**

还有一个**缩进**的问题需要后面接着注意

```
#严格来说这是python的一个嵌套结构
for i in range(1, 5, 2):
    if i//2 == 0:
        print("打死古优", i)
    else:
        print("干活古优", i)
```
```
#这个不太懂结果里面的道理，哦后来懂了，结尾i=i-1的作用
i = 5
while i != 0:
    if i %2 ==0:
        print(i)
    i = i -1   #注意这一行的缩进稍有不慎就是死循环，可以通过ctrl+c强制退出循环
```
```
#多重条件，“套娃”条件判断
a = 0
if a > 0:
  print("a是正数")
else:
  if a < 0:
    print("a是负数")
  else:
    print("a是0")
```
```
#上面那个也有更简洁的写法
a = 0
if a > 0:
  print("a是正数")
elseif a < 0:
  print("a是负数")
else:
  print("a是0")
```
## 跳转语句

### continue语句

仅对循环语句有用的玩意，就是跳过**某次符合条件的循环**

```
for i in range(0, 10):
  if i == 1:
    print("执行了continue")
    continue   #跳过该次循环的代码，继续下一次循环
  print(i)
print("循环语句")
```
<p>
测试一下，猜猜下一段代码的返回结果

```
a = 1
while a < 10:
  a = a + 2
  if a == 5:
    continue
  print(a)
```


### break语句

也是一种跳过语句，但是是跳出**全部循环**，同样只使用于循环语句

```
for i in range(5):
  if i == 2：
    break  #跳出全部循环
  print(i)
```
<p>

下面的这段代码演示了，一个break或一个continue只对应一个循环

```
for i in range(2):
  for j in range(3):
      if j == 1:
          continue #这个continue只管得了小循环，管不了外层的大循环
      print(i, j)
  print("结束第", i+1, "次循环")
```

## 函数的定义

```
def myfun(a, b):  #定义一个名为mtfun的函数接受输入变量a和变量b
    c = a + b     #在函数内部，创建了一个名为 c 的变量，它的值是 a 和 b 相加的结果
    return c      #这一行将变量 c 的值返回给函数的调用者

c = myfun(24, 23) #这里其实可以不用c=，直接可以得到返回的结果的
print(c)
```
以上代码向我们展示了一个简单函数的定义过程。def是灵魂。但是根据培训视频，这个东西有个严重的问题，就是函数和变量命名是没有意义的，而且关键字会和别的东西重复。如果你自己命名的东西变成了**橙色**，说明你占用了程序保留的关键字。

## 包的导入

一般我们有三个命令可以导入包，使用优先级分别是`conda`>`pip`>`wheel`

同时，这次的培训需要以下几个包：

1. nibabel：读取nii或者hdr文件
2. numpy：进行矩阵运算，已经自带
3. matplotlib：绘图，已经自带
4. seaborn：绘图
5. pandas：行为数据处理
6. scipy：读取matlab文件
7. scikit-learn：机器学习（这个的下载代码在培训中专门推荐：`pip install --upgrade scikit-learn`，但是为什么不也推荐`conda install -c conda-forge scikit-learn`呢）

### 通过conda实现

这个首先可以在下载anaconda的子程序`powershell prompt`里面输入命令实现

```
#假如我们要导入numpy或者卸掉numpy
conda install numpy
conda uninstall numpy
```

### 通过pip实现

在使用conda的时候，有些包是无法下载的，这个时候我们便可以试试用pip进行下载，同样我们在`powershell prompt`中进行

```
#假如我们还是要导入numpy或者卸掉numpy
pip install numpy
pip uninstall numpy
```

### 通过wheel实现

根据培训视频，如果前俩途径都没法导入我们想要的包，<https://www.lfd.uci.edu/~gohlke/pythonlibs/>，在网站里crtl+f，搜想要的包然后跟逛应用商店一样欸。不过这个要注意对应的python版本。

然后把下载好的包点着路径复制了，在`powershell prompt`里面输入`pip install D:\blablabla\blabla\blabla.whl`这样相当于再本地下载安装。